### ISSUE TITLE
ReferenceError: Cannot access 'getPostsMeta' before initialization

### ISSUE THREAD

**Issue by naaih** [oedotme/website#3]
<img width="503" alt="Screenshot 2021-12-05 101648" src="https://user-images.githubusercontent.com/24250947/144734680-8d1bc141-63e0-4168-acf4-bb9c2cf160c9.png">

**Comment by oedotme** [comment]
Could be `mdx-bundler` related. Here's a similar issue #https://github.com/kentcdodds/mdx-bundler/issues/110 by a missing `esbuild` dependency.

I'll add `esbuild` as a dependency just in case peer dependencies aren't installed.
